import { en } from './en';
import { ar } from './ar';

// Other languages inherit all keys from English with overridden navbar labels
const de = { ...en, navbar: { ...en.navbar, dashboard: "Armaturenbrett", categories: "Kategorien", cart: "Einkaufswagen", account: "Konto", searchPlaceholder: "MarketPlace durchsuchen", helloSignIn: "Hallo, Anmelden", login: "Anmelden", logout: "Abmelden", allCategories: "Alle Kategorien", browseCatalog: "Gesamten Katalog durchsuchen", volumeDeals: "Mengenrabatte", supplyPartners: "Lieferpartner", logisticsHelp: "Logistik-Hilfe", corporateAccounts: "Geschäftskonten" }, common: { ...en.common, search: "Suchen", approve: "Genehmigen", reject: "Ablehnen", cancel: "Abbrechen", save: "Speichern", loading: "Laden...", add: "Hinzufügen", edit: "Bearbeiten", delete: "Löschen", back: "Zurück" } };
const fr = { ...en, navbar: { ...en.navbar, dashboard: "Tableau de bord", categories: "Catégories", cart: "Panier", account: "Compte", searchPlaceholder: "Rechercher MarketPlace", helloSignIn: "Bonjour, Connexion", login: "Connexion", logout: "Déconnexion", allCategories: "Toutes les catégories", browseCatalog: "Parcourir le catalogue", volumeDeals: "Offres en volume", supplyPartners: "Partenaires", logisticsHelp: "Aide logistique", corporateAccounts: "Comptes entreprise" }, common: { ...en.common, search: "Chercher", approve: "Approuver", reject: "Rejeter", cancel: "Annuler", save: "Sauvegarder", loading: "Chargement...", add: "Ajouter", edit: "Modifier", delete: "Supprimer", back: "Retour" } };
const es = { ...en, navbar: { ...en.navbar, dashboard: "Panel", categories: "Categorías", cart: "Carrito", account: "Cuenta", searchPlaceholder: "Buscar en MarketPlace", helloSignIn: "Hola, Inicia sesión", login: "Iniciar sesión", logout: "Cerrar sesión", allCategories: "Todas las categorías", browseCatalog: "Ver todo el catálogo", volumeDeals: "Ofertas por volumen", supplyPartners: "Socios", logisticsHelp: "Ayuda logística", corporateAccounts: "Cuentas corporativas" }, common: { ...en.common, search: "Buscar", approve: "Aprobar", reject: "Rechazar", cancel: "Cancelar", save: "Guardar", loading: "Cargando...", add: "Agregar", edit: "Editar", delete: "Eliminar", back: "Volver" } };
const pt = { ...en, navbar: { ...en.navbar, dashboard: "Painel", categories: "Categorias", cart: "Carrinho", account: "Conta", searchPlaceholder: "Pesquisar no MarketPlace", helloSignIn: "Olá, Entre", login: "Entrar", logout: "Sair", allCategories: "Todas as categorias", browseCatalog: "Ver catálogo completo", volumeDeals: "Ofertas por volume", supplyPartners: "Parceiros", logisticsHelp: "Ajuda logística", corporateAccounts: "Contas empresariais" }, common: { ...en.common, search: "Pesquisar", approve: "Aprovar", reject: "Rejeitar", cancel: "Cancelar", save: "Salvar", loading: "Carregando...", add: "Adicionar", edit: "Editar", delete: "Excluir", back: "Voltar" } };
const ro = { ...en, navbar: { ...en.navbar, dashboard: "Panou", categories: "Categorii", cart: "Coș", account: "Cont", searchPlaceholder: "Caută pe MarketPlace", helloSignIn: "Bună, Autentificare", login: "Autentificare", logout: "Deconectare", allCategories: "Toate categoriile", browseCatalog: "Răsfoiește catalogul", volumeDeals: "Oferte de volum", supplyPartners: "Parteneri", logisticsHelp: "Ajutor logistic", corporateAccounts: "Conturi de firmă" }, common: { ...en.common, search: "Caută", approve: "Aprobă", reject: "Respinge", cancel: "Anulare", save: "Salvare", loading: "Se încarcă...", add: "Adaugă", edit: "Editare", delete: "Șterge", back: "Înapoi" } };

export const translations = {
    en, ar, de, fr, es, pt, ro
};

export type Locale = keyof typeof translations;
export type TranslationKey = keyof typeof en;
