export enum Role {
    SUPER_ADMIN = 'SUPER_ADMIN',
    PLATFORM_ADMIN = 'PLATFORM_ADMIN',
    FINANCE_ADMIN = 'FINANCE_ADMIN',
    OPS_ADMIN = 'OPS_ADMIN',
    CATEGORY_MANAGER = 'CATEGORY_MANAGER',
    SUPPLIER = 'SUPPLIER',
    BUYER = 'BUYER',
}
