import { Product } from '@/components/product/ProductCard';

export const PRODUCTS: Product[] = [
    // --- BEVERAGES ---
    {
        id: '1',
        name: 'Coca-Cola Original Taste, 330ml Can (Case of 24)',
        brand: 'Coca-Cola',
        price: 18.25,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Soft Drinks',
        bulkSave: true,
    },
    {
        id: '101',
        name: 'Bloom Sparkling Energy Cherry Lime, 12pk',
        brand: 'Bloom',
        price: 24.99,
        unit: 'case',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Energy Drinks',
    },
    {
        id: '2',
        name: 'Red Bull Energy Drink, 250ml (Case of 24)',
        brand: 'Red Bull',
        price: 34.50,
        unit: 'case',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Energy Drinks',
    },
    {
        id: '3',
        name: 'Pepsi Max No Sugar, 330ml Can (Case of 24)',
        brand: 'Pepsi',
        price: 17.50,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Soft Drinks',
    },
    {
        id: '102',
        name: 'Starbucks Frappuccino Coffee, 9.5 oz (12pk)',
        brand: 'Starbucks',
        price: 36.00,
        unit: 'case',
        minOrder: 3,
        image: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
    },
    {
        id: '103',
        name: 'Nescafe Classic Instant Coffee, 200g Tin',
        brand: 'Nescafe',
        price: 8.50,
        unit: 'unit',
        minOrder: 12,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
        bulkSave: true,
    },
    // --- SNACKS & CHOCOLATES ---
    {
        id: '201',
        name: 'Oreo Original Sandwich Biscuits, 154g (Pack of 16)',
        brand: 'Oreo',
        price: 22.40,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '202',
        name: 'KitKat 4 Finger Milk Chocolate Bar (Box of 24)',
        brand: 'KitKat',
        price: 19.20,
        unit: 'box',
        minOrder: 8,
        image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '203',
        name: 'Nutella Hazelnut Spread, 750g Jar',
        brand: 'Nutella',
        price: 6.50,
        unit: 'unit',
        minOrder: 12,
        image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    // --- PERSONAL CARE ---
    {
        id: '301',
        name: 'Dove Deeply Nourishing Body Wash, 500ml (Pack of 6)',
        brand: 'Dove',
        price: 28.50,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Personal Care',
        bulkSave: true,
    },
    {
        id: '302',
        name: 'Rexona Men Deodorant Spray, 150ml (Pack of 12)',
        brand: 'Rexona',
        price: 42.00,
        unit: 'box',
        minOrder: 2,
        image: 'https://images.unsplash.com/photo-1594122230689-45899d9e6f69?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Personal Care',
    },
    // --- HOME CARE ---
    {
        id: '401',
        name: 'Persil Liquid Laundry Detergent, 5L (Case of 2)',
        brand: 'Persil',
        price: 32.00,
        unit: 'case',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Home Care',
    },
    {
        id: '204',
        name: 'Snickers Chocolate Bar, 50g (Case of 24)',
        brand: 'Snickers',
        price: 21.60,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '205',
        name: 'M&M\'s Peanut Chocolate, 45g (Box of 24)',
        brand: 'm&m\'s',
        price: 24.00,
        unit: 'box',
        minOrder: 4,
        image: 'https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '104',
        name: 'Lavazza Qualita Oro Ground Coffee, 250g',
        brand: 'Lavazza',
        price: 7.20,
        unit: 'unit',
        minOrder: 20,
        image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
    },
    {
        id: '501',
        name: 'Doritos Nacho Cheese, 150g (Pack of 12)',
        brand: 'Doritos',
        price: 30.00,
        unit: 'box',
        minOrder: 2,
        image: 'https://images.unsplash.com/photo-1600952841320-db92ec4047ca?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '502',
        name: 'Pringles Original, 165g (Case of 12)',
        brand: 'Pringles',
        price: 28.50,
        unit: 'case',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '4',
        name: 'Fanta Orange, 330ml Can (Case of 24)',
        brand: 'Fanta',
        price: 17.50,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Soft Drinks',
    },
    {
        id: '210',
        name: 'Orbit Spearmint Sugar-Free Gum (Case of 24)',
        brand: 'Orbit',
        price: 15.60,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '211',
        name: 'Trident White Peppermint Gum (Box of 12)',
        brand: 'Trident',
        price: 12.00,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '105',
        name: 'Davidoff Rich Aroma Instant Coffee, 100g',
        brand: 'Davidoff',
        price: 9.80,
        unit: 'unit',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
    },
];

export const BRANDS = [
    'Coca-Cola', 'Pepsi', 'Red Bull', 'Bloom', 'Starbucks', 'Nescafe',
    'Fanta', 'Sprite', 'Dr Pepper', 'Lavazza', 'Davidoff', 'Jacobs',
    'Orbit', 'Trident', 'Mentos', 'Oreo', 'KitKat', 'Nutella', 'Mars',
    'Twix', 'Snickers', 'm&m\'s', 'Doritos', 'Pringles', 'Lay\'s', 'Takis',
    'Lindt', 'Ferrero Rocher', 'Dove', 'Rexona', 'Lifebuoy', 'Lux',
    'Persil', 'Comfort', 'Cif'
];

export const CATEGORIES_LIST = [
    'Soft Drinks', 'Energy Drinks', 'Coffee & Tea',
    'Snacks & Sweets', 'Personal Care', 'Home Care'
];
