export interface Product {
    id: string;
    name: string;
    brand: string;
    price: number;
    unit: string;
    minOrder: number;
    image: string;
    inStock: boolean;
    category: string;
    bulkSave?: boolean;
    rating?: number;
    reviews?: number;
}

export const PRODUCTS: Product[] = [
    // --- BEVERAGES ---
    {
        id: '1',
        name: 'Coca-Cola Original Taste, 330ml Can (Case of 24)',
        brand: 'Coca-Cola',
        price: 18.25,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Soft Drinks',
        bulkSave: true,
    },
    {
        id: '101',
        name: 'Bloom Sparkling Energy Cherry Lime, 12pk',
        brand: 'Bloom',
        price: 24.99,
        unit: 'case',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Energy Drinks',
    },
    {
        id: '2',
        name: 'Red Bull Energy Drink, 250ml (Case of 24)',
        brand: 'Red Bull',
        price: 34.50,
        unit: 'case',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Energy Drinks',
    },
    {
        id: '3',
        name: 'Pepsi Max No Sugar, 330ml Can (Case of 24)',
        brand: 'Pepsi',
        price: 17.50,
        unit: 'box',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1553456558-aff63285bdd1?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Soft Drinks',
    },
    {
        id: '102',
        name: 'Starbucks Frappuccino Coffee, 9.5 oz (12pk)',
        brand: 'Starbucks',
        price: 36.00,
        unit: 'case',
        minOrder: 3,
        image: 'https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
    },
    {
        id: '103',
        name: 'Nescafe Classic Instant Coffee, 200g Tin',
        brand: 'Nescafe',
        price: 8.50,
        unit: 'unit',
        minOrder: 12,
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Coffee & Tea',
        bulkSave: true,
    },
    // --- SNACKS & CHOCOLATES ---
    {
        id: '201',
        name: 'Oreo Original Sandwich Biscuits, 154g (Pack of 16)',
        brand: 'Oreo',
        price: 22.40,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '202',
        name: 'KitKat 4 Finger Milk Chocolate Bar (Box of 24)',
        brand: 'KitKat',
        price: 19.20,
        unit: 'box',
        minOrder: 8,
        image: 'https://images.unsplash.com/photo-1511381939415-e44015466834?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '203',
        name: 'Nutella Hazelnut Spread, 750g Jar',
        brand: 'Nutella',
        price: 6.50,
        unit: 'unit',
        minOrder: 12,
        image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Snacks & Sweets',
    },
    {
        id: '303',
        name: 'Gillette Fusion5 Razor Blades (Pack of 8)',
        brand: 'Gillette',
        price: 24.99,
        unit: 'box',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1626285492eda-fa605a9a4734?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Personal Care',
    },
    {
        id: '304',
        name: 'Pantene Pro-V Hair Fall Control Shampoo, 1L',
        brand: 'Pantene',
        price: 12.50,
        unit: 'unit',
        minOrder: 12,
        image: 'https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Personal Care',
    },
    // --- MAKEUP (Female & Male) ---
    {
        id: '701',
        name: 'Maybelline Fit Me Matte + Poreless Foundation',
        brand: 'Maybelline',
        price: 15.00,
        unit: 'unit',
        minOrder: 24,
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Makeup',
    },
    {
        id: '702',
        name: 'L\'Oréal Paris Voluminous Lash Paradise Mascara',
        brand: 'L\'Oréal',
        price: 12.00,
        unit: 'unit',
        minOrder: 36,
        image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Makeup',
    },
    {
        id: '703',
        name: 'War Paint for Men Foundation - Tinted Moisturizer',
        brand: 'War Paint',
        price: 32.00,
        unit: 'unit',
        minOrder: 10,
        image: 'https://images.unsplash.com/photo-1590156221122-c748c789d36a?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Makeup',
    },
    // --- PERFUME (Female & Male) ---
    {
        id: '801',
        name: 'Dior Sauvage Eau de Parfum for Men, 100ml',
        brand: 'Dior',
        price: 145.00,
        unit: 'unit',
        minOrder: 3,
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Perfume',
    },
    {
        id: '802',
        name: 'Chanel No. 5 Eau de Parfum for Women, 100ml',
        brand: 'Chanel',
        price: 165.00,
        unit: 'unit',
        minOrder: 2,
        image: 'https://images.unsplash.com/photo-1583467875263-d50dec37a88c?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Perfume',
    },
    {
        id: '803',
        name: 'Bleu de Chanel Parfum for Men, 150ml',
        brand: 'Chanel',
        price: 180.00,
        unit: 'unit',
        minOrder: 2,
        image: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Perfume',
    },
    {
        id: '804',
        name: 'Lancôme La Vie Est Belle, 75ml',
        brand: 'Lancôme',
        price: 110.00,
        unit: 'unit',
        minOrder: 5,
        image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Perfume',
    },
    // --- HOME CARE ---
    {
        id: '402',
        name: 'Ariel All-in-1 Pods Laundry Detergent, 60 Washes',
        brand: 'Ariel',
        price: 26.50,
        unit: 'unit',
        minOrder: 15,
        image: 'https://images.unsplash.com/photo-1583947581924-860bda6a26df?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Home Care',
    },
    {
        id: '403',
        name: 'Finish Powerball Quantum Dishwasher Tablets, 80ct',
        brand: 'Finish',
        price: 19.99,
        unit: 'unit',
        minOrder: 20,
        image: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=400&h=400&fit=crop',
        inStock: true,
        category: 'Home Care',
    },
];

export const BRANDS = [
    'Coca-Cola', 'Pepsi', 'Red Bull', 'Bloom', 'Starbucks', 'Nescafe',
    'Fanta', 'Sprite', 'Dr Pepper', 'Lavazza', 'Davidoff', 'Jacobs',
    'Orbit', 'Trident', 'Mentos', 'Oreo', 'KitKat', 'Nutella', 'Mars',
    'Twix', 'Snickers', 'm&m\'s', 'Doritos', 'Pringles', 'Lay\'s', 'Takis',
    'Lindt', 'Ferrero Rocher', 'Dove', 'Rexona', 'Lifebuoy', 'Lux',
    'Persil', 'Comfort', 'Cif', 'Red Rose', 'Bounty', 'Gillette', 'Pantene',
    'Maybelline', 'L\'Oréal', 'War Paint', 'Dior', 'Chanel', 'Lancôme',
    'Ariel', 'Finish'
];

export const CATEGORIES_LIST = [
    'Soft Drinks', 'Energy Drinks', 'Coffee & Tea',
    'Snacks & Sweets', 'Personal Care', 'Home Care',
    'Makeup', 'Perfume'
];
